language: go
env:
  - GO111MODULE=on
go:
    - "1.15"
script:
  - go test -v -race  ./...  # Run all the tests with the race detector enabled
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic # For code cov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODE_COV