version: 2.1
orbs:
  codecov: codecov/codecov@3.2.3
jobs:
  build:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Run tests and coverage
          command: go test -coverprofile=coverage.out
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build